name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: extractions/setup-just@v2
      - run: uv sync --all-groups
      - run: uv tool install ty
      - run: uv tool install ruff
      - run: just all
